/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/npnxeIdDICH
 */
import { Avatar } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import Image from "next/image"

export default function ICloudWebClient() {
  return (
    <div className="bg-[#007aff] min-h-screen p-10 flex justify-center items-center">
      <div className="flex justify-between items-start max-w-4xl w-full gap-10 px-10">
        <div className="space-y-6 w-3/5">
          <div className="bg-white rounded-lg p-4 shadow-lg transform transition-transform duration-200 hover:scale-105">
            <div className="flex items-center space-x-4">
              <div>
                <div className="text-lg font-semibold">John Doe</div>
                <div className="text-sm text-gray-500">johndoe@example.com</div>
                <Badge variant="secondary">iCloud+</Badge>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg p-4 shadow-lg transform transition-transform duration-200 hover:scale-105">
            <div className="flex justify-between items-center">
              <div className="text-lg font-semibold">Drive</div>
              <HistoryIcon className="text-blue-500" />
            </div>
            <div className="mt-2 space-y-1">
              <div className="flex items-center justify-between">
                <div className="text-sm">Medium size image.png</div>
                <FileIcon className="text-gray-400" />
              </div>
              <div className="flex items-center justify-between">
                <div className="text-sm">Small size image.jpg</div>
                <FileIcon className="text-gray-400" />
              </div>
              <div className="flex items-center justify-between">
                <div className="text-sm">Presentation.key</div>
                <FileIcon className="text-gray-400" />
              </div>
              <div className="text-right">
                <Button className="bg-white text-blue-500 hover:text-gray-200 transition-colors">...</Button>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg p-4 shadow-lg transform transition-transform duration-200 hover:scale-105">
            <div className="flex justify-between items-center">
              <div className="text-lg font-semibold">Notes</div>
              <CloudIcon className="text-blue-500" />
            </div>
            <div className="mt-2 space-y-1">
              <div className="text-sm">Important note</div>
              <div className="text-sm">Shopping list</div>
              <div className="text-right">
                <Button className="bg-white text-blue-500 hover:text-gray-200 transition-colors">...</Button>
              </div>
            </div>
          </div>
        </div>
        <div className="space-y-6 w-2/5">
          <div className="bg-white rounded-lg p-4 shadow-lg transform transition-transform duration-200 hover:scale-105">
            <div className="flex justify-between items-center">
              <MailIcon className="text-blue-500" />
              <Button className="text-sm" variant="outline">
                Configure
              </Button>
            </div>
            <div className="mt-2">
              <div className="text-lg font-semibold">Set up iCloud Mail</div>
              <div className="text-sm text-gray-500">Private, secure and personal email from Apple.</div>
            </div>
          </div>
          <div className="bg-white rounded-lg p-4 shadow-lg transform transition-transform duration-200 hover:scale-105">
            <div className="flex justify-between items-center">
              <div className="text-lg font-semibold">Photos</div>
              <CameraIcon className="text-blue-500" />
            </div>
            <div className="mt-2 grid grid-cols-3 gap-2">
              <Image
                alt="Photo 1"
                className="w-full h-auto rounded-md"
                height="60"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "60/60",
                  objectFit: "cover",
                }}
                width="60"
              />
              <Image
                alt="Photo 2"
                className="w-full h-auto rounded-md"
                height="60"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "60/60",
                  objectFit: "cover",
                }}
                width="60"
              />
              <Image
                alt="Photo 3"
                className="w-full h-auto rounded-md"
                height="60"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "60/60",
                  objectFit: "cover",
                }}
                width="60"
              />
            </div>
          </div>
          <div className="bg-white rounded-lg p-4 shadow-lg transform transition-transform duration-200 hover:scale-105">
            <div className="flex justify-between items-center">
              <div className="text-lg font-semibold">Reminders</div>
              <BellIcon className="text-blue-500" />
            </div>
            <div className="mt-2 space-y-1">
              <div className="flex items-center justify-between">
                <div className="text-sm">Meeting at 1 PM</div>
                <input className="form-checkbox h-5 w-5 text-blue-500" type="checkbox" />
              </div>
              <div className="flex items-center justify-between">
                <div className="text-sm">Call with client</div>
                <input className="form-checkbox h-5 w-5 text-blue-500" type="checkbox" />
              </div>
              <div className="text-right">
                <Button className="bg-white text-blue-500 hover:text-gray-200 transition-colors">...</Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function HistoryIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
      <path d="M3 3v5h5" />
      <path d="M12 7v5l4 2" />
    </svg>
  )
}


function FileIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}


function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function CloudIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function CameraIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>
  )
}


function BellIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}
